/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registro público de alumno */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Siempre 202 y sin cuerpo, exista o no una cuenta con ese email. Devolver 201 cuando se crea y 409 cuando ya existe permitiría enumerar usuarios, que es precisamente lo que prohíbe 02-arquitectura.md. Si el email ya estaba registrado no se crea nada y se avisa por correo al titular real de la dirección, como mucho una vez cada 5 minutos. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cuerpo que no pasa la validación (`VALIDATION_ERROR`), o una contraseña de más de 72 bytes (`AUTH_WEAK_PASSWORD`): bcrypt no usa el resto, y aceptarla engañaría a quien la eligió. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login correcto. El refresh token se fija en una cookie HttpOnly (`Set-Cookie`). */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Único resultado de cualquier fallo: email inexistente, contraseña incorrecta o cuenta desactivada. Distinguirlos revelaría qué direcciones tienen cuenta. Una cuenta pendiente de verificación SÍ puede iniciar sesión: la verificación condiciona reservar, no acceder (ver 13-fase5-analisis-identity.md, decisión 8.5). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout (revoca el refresh token actual)
         * @description Se autentica con la cookie `refresh_token`, no con el bearer token, y por eso exige el token CSRF. Responde 204 aunque no hubiera sesión: limpia la cookie en cualquier caso, para que el navegador no siga presentando una muerta.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesión cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["CsrfTokenMissing"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rota el access token usando el refresh token de la cookie
         * @description No lleva bearer token: se autentica con la cookie `refresh_token`. Por eso exige el token CSRF.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nuevo access token emitido; refresh token rotado (nueva cookie) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessTokenResponse"];
                    };
                };
                /** @description Refresh token ausente, expirado, revocado o reusado (familia revocada). Los cuatro casos responden exactamente lo mismo —`AUTH_SESSION_EXPIRED`, con la cookie limpiada— para no revelar cuál de ellos ocurrió. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                403: components["responses"]["CsrfTokenMissing"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifica el email con el token recibido por correo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyEmailRequest"];
                };
            };
            responses: {
                /** @description Email verificado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                /** @description La cuenta está desactivada (`AUTH_ACCOUNT_NOT_ACTIVE`): el enlace se pidió antes de desactivarla. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Token inválido, expirado o ya usado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verification-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenvía el enlace de verificación al usuario autenticado
         * @description Para quien perdió el correo o dejó caducar el enlace. Se pide con sesión, nunca por dirección: aceptar un email permitiría inundar el buzón de otro. Cuelga de /auth para que le aplique el límite por IP. Los enlaces anteriores siguen valiendo hasta caducar. Como mucho un reenvío cada 5 minutos; dentro de ese plazo responde igual y no envía nada.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enviado, o nada que enviar porque la dirección ya estaba verificada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicita un email de recuperación de contraseña */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Siempre 202, exista o no la cuenta, para no permitir enumeración de usuarios (ver 02-arquitectura.md). Como mucho un correo cada 5 minutos por dirección. Al restablecer la contraseña con un enlace, los demás dejan de valer. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablece la contraseña con el token recibido por correo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description Contraseña actualizada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cuerpo que no pasa la validación (`VALIDATION_ERROR`), o una contraseña de más de 72 bytes (`AUTH_WEAK_PASSWORD`): bcrypt no usa el resto, y aceptarla engañaría a quien la eligió. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description La cuenta está desactivada (`AUTH_ACCOUNT_NOT_ACTIVE`): el enlace se pidió antes de desactivarla. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Token inválido, expirado o ya usado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualiza campos de perfil propios (solo los aplicables al rol del usuario) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Validación de campos, o un campo que no corresponde al rol del usuario (`FIELD_NOT_APPLICABLE_TO_ROLE`). El rol, el email y el estado de la cuenta no son campos de este endpoint: si llegan en el cuerpo se ignoran, nunca se aplican. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/teacher/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfil público/operativo del profesor único
         * @description Solo lectura. El profesor cambia su perfil con PATCH /me, como cualquier usuario.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeacherProfile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de alumnos gestionados por el profesor */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    /** @description Filtro parcial por nombre o email, **restringido a los alumnos que este profesor ya gestiona**. Para localizar a un alumno cualquiera del sistema se usa `/teacher/students/lookup`, que exige el email exacto: una búsqueda parcial sobre todas las cuentas permitiría enumerar quién está registrado en la plataforma. */
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentSummaryPage"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/students/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Localiza un alumno por email exacto, antes de asociarlo
         * @description Solo acepta la dirección completa: ni prefijos, ni comodines, ni coincidencias parciales. Quien va a asociar a un alumno conoce su email y no necesita explorar. La respuesta no incluye DNI ni dirección.
         */
        get: {
            parameters: {
                query: {
                    /** @description Dirección completa, sin distinguir mayúsculas */
                    email: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentLookup"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Ninguna cuenta de alumno tiene esa dirección */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/students/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha completa de un alumno gestionado
         * @description Incluye `nationalId` y `address`, que son datos personales de acceso restringido. Solo responde al profesor que gestiona a ese alumno: conocer el UUID no basta.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentDetail"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description El llamante no es el profesor (`TEACHER_FORBIDDEN`), o no gestiona a ese alumno (`STUDENT_NOT_MANAGED`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/students/{userId}/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asocia un alumno registrado como gestionado (búsqueda previa por email)
         * @description Si el alumno estaba desactivado, lo reactiva reutilizando la misma relación. El límite de alumnos de `platform_configuration` se aplica también en ese caso.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alumno gestionado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentSummary"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description No existe una cuenta de alumno con ese id (`STUDENT_NOT_FOUND`) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description El alumno ya está gestionado (`STUDENT_ALREADY_MANAGED`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description El alumno todavía no ha rellenado sus datos personales (`STUDENT_PROFILE_INCOMPLETE`), o se alcanzó el límite de alumnos (`STUDENT_LIMIT_REACHED`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        /**
         * Desactiva la gestión de un alumno
         * @description Marca la relación como `INACTIVE` y registra `deactivatedAt`; la fila no se borra, para que volver a asociarlo reutilice la relación en vez de crear una segunda.
         *     Cancela en la misma transaccion las reservas confirmadas del alumno en clases de este profesor que aun no han empezado (`CANCELLED_BY_TEACHER`), como exige `01-analisis-funcional.md`. Las de clases ya empezadas se conservan: son historico.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alumno desactivado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description El llamante no es el profesor (`TEACHER_FORBIDDEN`), o nunca gestionó a ese alumno (`STUDENT_NOT_MANAGED`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description El alumno ya estaba desactivado (`STUDENT_ALREADY_INACTIVE`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reglas semanales y excepciones de un rango de fechas
         * @description Legible por cualquier usuario autenticado, igual que el perfil del profesor: un alumno necesita saber cuándo trabaja su profesor. El rango es obligatorio y acota **solo las excepciones** —las reglas semanales se devuelven enteras, porque son un conjunto pequeño—. Sin tope, la respuesta crecería cada temporada sin límite.
         */
        get: {
            parameters: {
                query: {
                    from: string;
                    /** @description Como máximo 62 días después de `from`, ambos incluidos. */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailabilityResponse"];
                    };
                };
                /** @description Rango inválido o más ancho de 62 días (`DATE_RANGE_INVALID`) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/availability/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reemplaza el conjunto completo de reglas semanales
         * @description **No fusiona: reemplaza.** Una regla que el cliente no envíe deja de existir, incluida una cuyo `activeFrom` todavía esté en el futuro. Por eso el `GET` devuelve `activeFrom` y `activeUntil`: el ciclo leer-editar-escribir tiene que poder reenviar todo lo que leyó. Una lista vacía es válida y significa "no tengo horario semanal fijo".
         *     El conjunto se valida entero antes de escribir nada, así que una petición rechazada deja la configuración anterior intacta.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WeeklyAvailabilityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeeklyAvailabilityResponse"];
                    };
                };
                /** @description Dos reglas del mismo día se pisan (`AVAILABILITY_RULES_OVERLAP`), o una regla es inválida: día desconocido, fin no posterior al inicio (`AVAILABILITY_INVALID`). Tocarse no es solaparse: 09:00-11:00 y 11:00-13:00 son válidas. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/availability/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea un bloqueo o disponibilidad extraordinaria para una fecha
         * @description Las excepciones solapadas se aceptan: dos bloqueos que cubren las mismas horas bloquean lo mismo, y dos extras suman lo mismo. Cuando una fecha tiene a la vez un `BLOCK` y un `EXTRA`, **manda el bloqueo**: equivocarse hacia "no disponible" cuesta un hueco, equivocarse al revés pone al profesor a dar clase el día que dijo que no podía.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAvailabilityExceptionRequest"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailabilityException"];
                    };
                };
                /** @description `EXTRA` sin horas, media hora suelta, fin no posterior al inicio o tipo desconocido (`AVAILABILITY_INVALID`) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/availability/exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Elimina una excepción de disponibilidad */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description No existe (`AVAILABILITY_EXCEPTION_NOT_FOUND`). Un id de otro profesor responde lo mismo: un 403 confirmaría que el id existe. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendario de un rango de dias, para el profesor o para el alumno
         * @description Las fechas se leen en la zona del profesor (timezone en la respuesta), con el tope comun de 62 dias. El profesor recibe su disponibilidad resuelta en intervalos y todas sus clases, canceladas incluidas. El alumno recibe las clases de los profesores que lo gestionan, sin las canceladas salvo que tuviera reserva en ellas, y en cada una su propia reserva (myBooking). Un alumno no gestionado recibe listas vacias. Sin notes para nadie.
         */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Calendar"];
                    };
                };
                /** @description DATE_RANGE_INVALID, o fechas mal formadas (VALIDATION_ERROR) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description AUTH_FORBIDDEN, si quien llama no es profesor ni alumno */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea una clase individual o grupal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLessonRequest"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lesson"];
                    };
                };
                /** @description LESSON_INVALID: duracion que no es multiplo de 30, fin antes del inicio, o la clase cruza medianoche en la zona del profesor. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description LESSON_OVERLAP */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description LESSON_OUTSIDE_AVAILABILITY: la clase cae fuera del horario configurado y no se pidio overrideAvailability. Releer la disponibilidad no cambia la respuesta: o se mueve la clase o se fuerza a proposito. LESSON_IN_THE_PAST (Fase 9): la clase empezaria en el instante de crearla o antes; no podria tener reservas ni, por tanto, asistencia. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una clase */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lesson"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserva la clase para el alumno autenticado
         * @description Confirmada al instante. Bloquea la fila de la clase (SELECT ... FOR UPDATE) antes de contar plazas, de modo que dos peticiones por la ultima plaza hacen cola y solo una gana. Solo para alumnos con el email verificado y gestionados por el profesor de la clase. Se puede reservar hasta el inicio de la clase; quien reserva con menos de 24 horas ya no podra cancelar, y el cliente deberia avisarlo antes de confirmar.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reserva confirmada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description STUDENT_NOT_MANAGED: el profesor de la clase no gestiona al alumno, o lo desactivo. EMAIL_NOT_VERIFIED: el alumno no ha verificado su direccion. AUTH_FORBIDDEN: quien llama no es un alumno. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description LESSON_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description LESSON_FULL | BOOKING_ALREADY_EXISTS | STUDENT_SCHEDULE_OVERLAP | LESSON_NOT_BOOKABLE (la clase esta cancelada). En los cuatro casos la pantalla del cliente esta obsoleta: releer la clase puede cambiar la respuesta. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description LESSON_ALREADY_STARTED */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reservas del alumno autenticado, o de las clases del profesor si lo consulta el profesor
         * @description Ordenadas por la clase mas reciente primero. El profesor puede filtrar por lessonId, que es lo que construye la pantalla de asistencia. Un lessonId de una clase ajena devuelve una pagina vacia, no las reservas de otro.
         */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    status?: components["schemas"]["BookingStatus"];
                    /** @description Solo para el profesor; el alumno ya ve unicamente las suyas. */
                    lessonId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingPage"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description AUTH_FORBIDDEN, si quien llama no es alumno ni profesor */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela una reserva
         * @description El alumno cancela las suyas con al menos 24 horas de antelacion (CANCELLED_BY_STUDENT). El profesor cancela cualquiera de sus clases sin ventana (CANCELLED_BY_TEACHER), por la misma razon por la que puede cancelar la clase entera. El admin cancela cualquiera sin ventana (CANCELLED_BY_ADMIN). Nadie cancela una reserva de una clase que ya empezo: a partir de ese momento lo que toca es marcar asistencia.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description BOOKING_NOT_FOUND, tambien cuando la reserva existe pero no es de quien llama: confirmar que un id existe es decir algo que no tenia por que saber. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description BOOKING_ALREADY_CANCELLED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description CANCELLATION_WINDOW_EXPIRED (solo alumno, menos de 24 horas) | LESSON_ALREADY_STARTED */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/lessons/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela una clase completa
         * @description El profesor puede cancelar su propia clase en cualquier momento. La ventana de 24 horas NO le ata: un profesor que enferma la noche antes tiene que poder cancelar. La ventana sigue intacta para el alumno que cancela su reserva, que es donde el producto la justifico. La respuesta trae cancelledAtShortNotice para que el cliente sepa si hubo menos de 24 horas de aviso. Cancela en cascada, en la misma transaccion, todas sus reservas confirmadas (CANCELLED_BY_TEACHER): si la cascada falla, la clase no queda cancelada.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lesson"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description LESSON_ALREADY_CANCELLED: ya estaba cancelada, casi siempre una pantalla obsoleta */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description LESSON_ALREADY_FINISHED: la clase ya termino. Cancelar algo que ya ocurrio es reescribir el pasado. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/lessons/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marca asistencia de los participantes de una clase
         * @description Lo sirve el modulo booking aunque la ruta cuelgue de /teacher/lessons: el cuerpo son bookingId y la respuesta son reservas. Solo a partir del inicio de la clase, solo sobre reservas confirmadas de esa clase, y todo o nada: si una entrada no se puede aplicar, no se aplica ninguna. Se puede corregir: marcar de nuevo sustituye lo anterior.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MarkAttendanceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"][];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description TEACHER_FORBIDDEN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description BOOKING_NOT_FOUND, si alguna entrada no es una reserva de esta clase y de este profesor */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description BOOKING_ALREADY_CANCELLED, si alguna entrada es una reserva cancelada */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description ATTENDANCE_NOT_YET_OPEN */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuración global de la plataforma */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformConfiguration"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description AUTH_FORBIDDEN, si quien llama no es ADMIN (igual en todo /admin) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambia el límite de alumnos y la capacidad máxima de grupo
         * @description Los dos campos son opcionales: el que no se envía conserva su valor. Bajar el límite por debajo de los alumnos ya gestionados se permite: no echa a nadie, sólo impide gestionar nuevos. Las clases ya creadas conservan su capacidad. Registra updatedAt y updatedBy.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateConfigurationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformConfiguration"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de usuarios de la plataforma, la más reciente primero */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    role?: components["schemas"]["Role"];
                    status?: components["schemas"]["UserStatus"];
                    /** @description Parte del email, sin distinguir mayúsculas. Al profesor se le niega la búsqueda parcial para que no pueda enumerar cuentas; el admin ya puede verlas todas. */
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserSummaryPage"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activa o desactiva la cuenta de un alumno
         * @description Desactivar cierra sus sesiones (el access token vivo caduca en 15 minutos como mucho), hace que el profesor deje de gestionarlo y cancela sus reservas futuras como CANCELLED_BY_ADMIN. Reactivar devuelve ACTIVE si había verificado el email y PENDING_VERIFICATION si no; no vuelve a quedar gestionado, eso lo decide el profesor.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserSummary"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description AUTH_FORBIDDEN si quien llama no es ADMIN; ADMIN_TARGET_NOT_ALLOWED si la cuenta no es de un alumno. Desactivar al único profesor apagaría la plataforma, y un admin que desactiva a otro, o a sí mismo, puede quedarse sin nadie que lo deshaga. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description USER_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /**
             * @description Código de negocio, ver 11-contrato-api.md
             * @example LESSON_FULL
             */
            code?: string;
            instance?: string;
            /** @description Solo en VALIDATION_ERROR de un cuerpo, un elemento por campo rechazado */
            errors?: {
                field: string;
                message: string;
            }[];
        };
        /** @enum {string} */
        Role: "ADMIN" | "TEACHER" | "STUDENT";
        /** @enum {string} */
        UserStatus: "PENDING_VERIFICATION" | "ACTIVE" | "DISABLED";
        /** @enum {string} */
        LessonType: "INDIVIDUAL" | "GROUP";
        /** @enum {string} */
        LessonStatus: "OPEN" | "FULL" | "CANCELLED" | "COMPLETED";
        /**
         * @description Si la reserva sigue en pie y, si no, quien la termino. La asistencia NO esta aqui desde la Fase 9: ATTENDED y NO_SHOW sacaban la reserva de CONFIRMED y, con ello, del indice unico, de la restriccion de solapamiento y del recuento de plazas. Ver Attendance.
         * @enum {string}
         */
        BookingStatus: "CONFIRMED" | "CANCELLED_BY_STUDENT" | "CANCELLED_BY_TEACHER" | "CANCELLED_BY_ADMIN";
        /** @enum {string} */
        Attendance: "PENDING" | "ATTENDED" | "NO_SHOW";
        /** @enum {string} */
        ManagedStatus: "MANAGED" | "INACTIVE";
        UserSummary: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
        };
        /** @description fullName se retira hasta la Fase 6: el nombre vive en student_profiles, tabla que todavía no existe. Aceptar el campo y descartarlo haría creer al cliente que se ha guardado. Volverá cuando el módulo student pueda persistirlo. */
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            user: components["schemas"]["UserSummary"];
        };
        AccessTokenResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
        };
        VerifyEmailRequest: {
            token: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            /** Format: password */
            newPassword: string;
        };
        /** @description Forma única para todos los roles: los campos que no aplican llegan a `null`. Un alumno recién verificado que aún no ha rellenado sus datos recibe `fullName`, `phone`, `nationalId` y `address` a `null`, y esa ausencia es la señal de que el frontend debe pedírselos. */
        MeResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            emailVerifiedAt: string | null;
            /** @description Solo STUDENT */
            fullName: string | null;
            phone: string | null;
            /** @description Solo STUDENT. Dato restringido: solo visible para el propio usuario, el profesor que lo gestiona o un ADMIN */
            nationalId: string | null;
            /** @description Solo STUDENT. Dato restringido, igual que nationalId */
            address: string | null;
            /** @description Solo TEACHER */
            displayName: string | null;
            /** @description Solo TEACHER. Id IANA, p.ej. Europe/Madrid */
            timezone: string | null;
        };
        /**
         * @description Solo se aceptan los campos aplicables al rol del usuario autenticado. Enviar uno de otro rol responde `400` con código `FIELD_NOT_APPLICABLE_TO_ROLE`, en lugar de ignorarlo: un cambio descartado en silencio hace creer al cliente que guardó.
         *     El primer `PATCH` de un alumno debe llevar `fullName`, porque es cuando nace su perfil. Los siguientes pueden ser parciales; una cadena vacía borra un campo opcional.
         */
        UpdateMeRequest: {
            /** @description Solo STUDENT */
            fullName?: string;
            phone?: string;
            /** @description Solo STUDENT */
            nationalId?: string;
            /** @description Solo STUDENT */
            address?: string;
            /** @description Solo TEACHER */
            displayName?: string;
            /** @description Solo TEACHER */
            timezone?: string;
        };
        TeacherProfile: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            phone: string | null;
            /** @example Europe/Madrid */
            timezone: string;
        };
        StudentSummary: {
            /** Format: uuid */
            userId: string;
            fullName: string;
            /** Format: email */
            email: string;
            managedStatus: components["schemas"]["ManagedStatus"];
            /** Format: date-time */
            managedAt: string | null;
        };
        /** @description Lo mínimo para confirmar a quién se va a asociar. Sin teléfono, DNI ni dirección. */
        StudentLookup: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            /** @description null si el alumno aún no ha rellenado sus datos */
            fullName: string | null;
            /**
             * @description null cuando todavía no existe relación con este profesor. Repite los valores de ManagedStatus en vez de referenciarlo: en OpenAPI 3.0 un nullable junto a un $ref o un allOf no tiene efecto, y el null quedaba fuera del contrato.
             * @enum {string|null}
             */
            managedStatus: "MANAGED" | "INACTIVE" | null;
        };
        /** @description Ficha completa de un alumno gestionado, con los datos restringidos. Nunca se devuelve en listados ni búsquedas. */
        StudentDetail: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            fullName: string;
            phone: string | null;
            nationalId: string | null;
            address: string | null;
            managedStatus: components["schemas"]["ManagedStatus"];
            /** Format: date-time */
            managedAt: string;
            /** Format: date-time */
            deactivatedAt: string | null;
        };
        StudentSummaryPage: components["schemas"]["Page"] & {
            items: components["schemas"]["StudentSummary"][];
        };
        /**
         * @description Hora de pared en la zona del profesor, sin fecha y sin desplazamiento. **Se devuelve siempre como `HH:mm:ss`**; a la entrada se acepta también `HH:mm`. No es un instante: a qué momento corresponde depende de la fecha y de la zona horaria del profesor.
         * @example 09:00:00
         */
        LocalTime: string;
        /**
         * @description Nombre ISO-8601 del día. Es un nombre y no un número a propósito: alrededor de este campo se cruzan tres convenciones —el borrador de este contrato decía 0 = lunes, `java.time.DayOfWeek` numera el lunes 1 y `EXTRACT(DOW)` de PostgreSQL numera el domingo 0— y un número equivocado no falla en ninguna capa: mueve el horario un día. Un nombre equivocado no se puede interpretar.
         * @enum {string}
         */
        DayOfWeek: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
        WeeklyAvailabilityRule: {
            /** Format: uuid */
            id: string;
            dayOfWeek: components["schemas"]["DayOfWeek"];
            startTime: components["schemas"]["LocalTime"];
            endTime: components["schemas"]["LocalTime"];
            /**
             * Format: date
             * @description Null = aplica desde siempre. Ambos extremos son inclusivos.
             */
            activeFrom: string | null;
            /** Format: date */
            activeUntil: string | null;
        };
        WeeklyAvailabilityRequest: {
            /** @description El conjunto completo. Una lista vacía es válida: significa que no hay horario semanal fijo. */
            rules: {
                dayOfWeek: components["schemas"]["DayOfWeek"];
                startTime: components["schemas"]["LocalTime"];
                endTime: components["schemas"]["LocalTime"];
                /** Format: date */
                activeFrom?: string | null;
                /** Format: date */
                activeUntil?: string | null;
            }[];
        };
        WeeklyAvailabilityResponse: {
            rules: components["schemas"]["WeeklyAvailabilityRule"][];
        };
        AvailabilityException: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            /** @description Null en un `BLOCK` significa el día entero. En un `EXTRA` nunca es null. */
            startTime: string | null;
            endTime: string | null;
            /** @enum {string} */
            type: "BLOCK" | "EXTRA";
        };
        CreateAvailabilityExceptionRequest: {
            /** Format: date */
            date: string;
            /** @description Obligatoria en un `EXTRA`. En un `BLOCK`, omitir las dos horas bloquea el día entero; enviar una sola de las dos se rechaza, porque no describe nada. */
            startTime?: string | null;
            endTime?: string | null;
            /** @enum {string} */
            type: "BLOCK" | "EXTRA";
        };
        AvailabilityResponse: {
            weeklyRules: components["schemas"]["WeeklyAvailabilityRule"][];
            exceptions: components["schemas"]["AvailabilityException"][];
        };
        Calendar: {
            /** @description Zona IANA del profesor; null si el alumno no esta gestionado */
            timezone: string | null;
            availability: {
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string;
            }[];
            lessons: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                teacherUserId: string;
                type: components["schemas"]["LessonType"];
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string;
                capacity: number;
                bookedCount: number;
                status: components["schemas"]["LessonStatus"];
                myBooking: {
                    /** Format: uuid */
                    id: string;
                    status: components["schemas"]["BookingStatus"];
                    attendance: components["schemas"]["Attendance"];
                } | null;
            }[];
        };
        CreateLessonRequest: {
            type: components["schemas"]["LessonType"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @description Una clase INDIVIDUAL tiene capacidad exactamente 1. Una GROUP va de 1 hasta el tope configurado en platform_configuration.max_group_capacity, 8 por defecto. */
            capacity: number;
            notes?: string | null;
            /**
             * @description Permite crear la clase fuera de la disponibilidad configurada
             * @default false
             */
            overrideAvailability: boolean;
        };
        /**
         * @description bookedCount es el numero de reservas confirmadas. Se retiro en la Fase 8, cuando solo booking podia contarlas y aun no existia, y volvio con la Fase 9.
         *     status se calcula al leer y no se guarda. La columna solo tiene OPEN y CANCELLED, que es lo que decide una persona; COMPLETED se deduce del reloj y FULL del numero de reservas. Precedencia: CANCELLED, luego COMPLETED, luego FULL, luego OPEN. Una clase llena que ya termino es COMPLETED: de una clase pasada lo que importa es que ocurrio.
         *     notes es del profesor. Viaja como null para cualquier otro llamante: es texto libre que el profesor escribe para si mismo, no para que lo lea el alumno.
         */
        Lesson: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teacherUserId: string;
            type: components["schemas"]["LessonType"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            capacity: number;
            bookedCount: number;
            status: components["schemas"]["LessonStatus"];
            notes: string | null;
            createdOutsideAvailability: boolean;
            /** Format: date-time */
            cancelledAt: string | null;
            /** @description Si la cancelacion dejo menos de 24 horas. Derivado de cancelledAt y startsAt. */
            cancelledAtShortNotice: boolean;
        };
        /** @description lesson viaja sin notes para todos: las notas son del profesor y se leen en la propia clase, donde se decide quien las ve. Repetir esa regla aqui seria una segunda copia. */
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lessonId: string;
            /** Format: uuid */
            studentUserId: string;
            status: components["schemas"]["BookingStatus"];
            attendance: components["schemas"]["Attendance"];
            /** Format: date-time */
            bookedAt: string;
            /** Format: date-time */
            cancelledAt: string | null;
            lesson: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                teacherUserId: string;
                type: components["schemas"]["LessonType"];
                /** Format: date-time */
                startsAt: string;
                /** Format: date-time */
                endsAt: string;
                capacity: number;
                bookedCount: number;
                status: components["schemas"]["LessonStatus"];
            };
        };
        BookingPage: components["schemas"]["Page"] & {
            items: components["schemas"]["Booking"][];
        };
        MarkAttendanceRequest: {
            entries: {
                /** Format: uuid */
                bookingId: string;
                /** @enum {string} */
                status: "ATTENDED" | "NO_SHOW";
            }[];
        };
        PlatformConfiguration: {
            studentLimit: number;
            /** @description Tope de plazas de una clase grupal, anadido en la Fase 8. Configurable y no una constante del codigo: el dia que el numero este mal, lo estara para todas las clases a la vez. */
            maxGroupCapacity: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uuid */
            updatedBy: string | null;
        };
        UpdateConfigurationRequest: {
            studentLimit?: number;
            maxGroupCapacity?: number;
        };
        AdminUserSummary: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserSummaryPage: components["schemas"]["Page"] & {
            items: components["schemas"]["AdminUserSummary"][];
        };
        UpdateUserStatusRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
        };
        Page: {
            page: number;
            size: number;
            totalItems: number;
        };
    };
    responses: {
        /** @description No autenticado o token expirado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Autenticado pero sin permiso o relación sobre el recurso */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Falta la cabecera `X-XSRF-TOKEN` o su valor no coincide con la cookie `XSRF-TOKEN` (`code`: `AUTH_CSRF_TOKEN_INVALID`). No es un problema de permisos: el cliente debe reenviar la petición con la cabecera puesta. */
        CsrfTokenMissing: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Cuerpo, id o parámetro mal formados, o un campo que no pasa la validación (`VALIDATION_ERROR`) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Demasiados intentos desde la misma IP (`AUTH_RATE_LIMITED`). Todo /auth comparte el límite; la cabecera Retry-After dice cuántos segundos esperar. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        Id: string;
        UserId: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
